# Generated by Django 5.1.4 on 2026-01-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(help_text='PK', primary_key=True, serialize=False)),
                ('clerk_id', models.CharField(help_text='Clerk User ID', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
