# Generated by Django 6.0.1 on 2026-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('clerk_id', models.CharField(help_text='Clerk User ID', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='이름', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, help_text='성', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Admin 사이트 접근 권한')),
                ('is_superuser', models.BooleanField(default=False, help_text='모든 권한을 가진 슈퍼유저')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
