# Generated by Django 6.0.1 on 2026-01-15 14:41

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def set_unusable_password(apps, schema_editor):
    """기존 사용자들에게 사용 불가능한 password 설정"""
    User = apps.get_model('users', 'User')
    # AbstractBaseUser의 password 필드는 이미 추가되어 있으므로
    # 기존 사용자들에게 사용 불가능한 password를 설정
    for user in User.objects.all():
        if not user.password:
            user.password = make_password(None)  # 사용 불가능한 password
            user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_id_user_id'),
        ('auth', '0012_alter_user_first_name_max_length'),  # AbstractBaseUser가 auth 앱에 의존
    ]

    operations = [
        # password 필드 추가 (AbstractBaseUser에서 상속)
        # 먼저 임시 기본값으로 추가
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='unusable', max_length=128, verbose_name='password'),
            preserve_default=True,
        ),
        # last_login 필드 추가 (AbstractBaseUser에서 상속)
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        # email 필드를 null 허용으로 변경
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        # 기존 사용자들에게 사용 불가능한 password 설정
        migrations.RunPython(set_unusable_password, migrations.RunPython.noop),
    ]
