# Generated by Django 6.0.1 on 2026-01-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
