# Generated by Django 6.0.1 on 2026-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('고소장', '고소장'), ('내용증명서', '내용증명서'), ('합의서', '합의서')], default='고소장', max_length=100, verbose_name='템플릿 타입')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('고소장', '고소장'), ('내용증명서', '내용증명서    '), ('합의서', '합의서')], default='고소장', max_length=100, verbose_name='템플릿 타입')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
