# Generated by Django 6.0.1 on 2026-01-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, help_text='문서 유형 (예: criminal_complaint_fraud)', max_length=100)),
                ('name', models.CharField(help_text='템플릿 이름', max_length=200)),
                ('version', models.PositiveIntegerField(default=1, help_text='템플릿 버전')),
                ('content_md', models.TextField(help_text='Markdown 형식의 템플릿 내용 ({{variable_name}} 플레이스홀더 포함)')),
                ('variables', models.JSONField(default=list, help_text='템플릿에서 사용하는 변수 목록')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문서 템플릿',
                'verbose_name_plural': '문서 템플릿들',
                'db_table': 'document_templates',
                'ordering': ['-created_at'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, help_text='연관된 케이스 ID (선택)', max_length=100, null=True)),
                ('content_md', models.TextField(help_text='생성된 Markdown 문서 내용')),
                ('validation_result', models.JSONField(default=dict, help_text='검증 결과 (pass, errors)')),
                ('input_values', models.JSONField(default=dict, help_text='입력된 변수 값들')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(help_text='사용된 템플릿', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.template')),
            ],
            options={
                'verbose_name': '생성된 문서',
                'verbose_name_plural': '생성된 문서들',
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
