# Generated by Django 6.0.1 on 2026-01-23 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(db_index=True, help_text='연관된 케이스 ID')),
                ('document_type', models.CharField(help_text='문서 유형 (한글 또는 영문)', max_length=100)),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('extracting', '값 추출 중'), ('questioning', '추가 질문 중'), ('generating', '문서 생성 중'), ('completed', '완료'), ('failed', '실패')], default='waiting', help_text='세션 상태', max_length=20)),
                ('values', models.JSONField(default=dict, help_text='수집된 변수 값들')),
                ('required_keys', models.JSONField(default=list, help_text='필수 변수 키 목록')),
                ('last_draft', models.TextField(blank=True, help_text='최근 생성된 문서 초안', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='최종 생성된 문서', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='documents.document')),
                ('template', models.ForeignKey(help_text='사용할 템플릿', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='documents.template')),
            ],
            options={
                'verbose_name': '문서 작성 세션',
                'verbose_name_plural': '문서 작성 세션들',
                'db_table': 'document_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '어시스턴트'), ('system', '시스템')], help_text='메시지 역할', max_length=20)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('extracted_values', models.JSONField(blank=True, default=dict, help_text='이 메시지에서 추출된 값들')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='연관된 세션', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.documentsession')),
            ],
            options={
                'verbose_name': '세션 메시지',
                'verbose_name_plural': '세션 메시지들',
                'db_table': 'document_session_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
