# Generated by Django 6.0.1 on 2026-01-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('complaint', '고소장'), ('notice', '내용증명서'), ('agreement', '합의서')], default='complaint', max_length=100, verbose_name='문서 타입'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('complaint', '고소장'), ('notice', '내용증명서'), ('agreement', '합의서')], default='complaint', max_length=100, verbose_name='템플릿 타입'),
        ),
    ]
