# Generated by Django 6.0.1 on 2026-01-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='clerk_user_id',
        ),
    ]
