# Generated by Django 6.0 on 2026-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_user_id_session_clerk_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='clerk_user_id',
            field=models.CharField(max_length=50),
        ),
    ]
