# Generated by Django 6.0.1 on 2026-01-15 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_user_id_session_clerk_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '채팅 세션', 'verbose_name_plural': '채팅 세션 목록'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='clerk_user_id',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
