# Generated by Django 6.0 on 2026-01-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_session_clerk_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='clerk_user_id',
            field=models.IntegerField(),
        ),
    ]
