# Generated by Django 6.0.1 on 2026-01-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_session_options_remove_session_clerk_user_id_and_more'),
    ]

    operations = [
    ]
