# Generated by Django 6.0.1 on 2026-01-15 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('category_code', models.IntegerField(verbose_name='대분류 코드')),
                ('category_name', models.CharField(max_length=50, verbose_name='대분류명')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('court_code', models.IntegerField(verbose_name='법원코드')),
                ('court_type', models.CharField(choices=[('대법원', '대법원'), ('고등법원', '고등법원'), ('지방법원', '지방법원')], max_length=20, verbose_name='법원 타입')),
                ('court_name', models.CharField(max_length=50, verbose_name='법원명')),
            ],
            options={
                'db_table': 'courts',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('name', models.CharField(max_length=200, verbose_name='키워드')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('outcome_code', models.IntegerField(verbose_name='결과 코드')),
                ('outcome_type', models.CharField(max_length=50, verbose_name='결과 이름')),
            ],
            options={
                'db_table': 'outcomes',
            },
        ),
        migrations.CreateModel(
            name='ReferenceCourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('ref_case_no', models.CharField(max_length=50, verbose_name='사건번호')),
            ],
            options={
                'db_table': 'reference_court_cases',
            },
        ),
        migrations.CreateModel(
            name='ReferenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('law_type', models.CharField(max_length=50, verbose_name='법률명')),
                ('article_no', models.IntegerField(verbose_name='조문')),
            ],
            options={
                'db_table': 'reference_rules',
            },
        ),
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('case_no', models.CharField(max_length=50, verbose_name='사건번호')),
                ('case_name', models.CharField(max_length=50, verbose_name='사건명')),
                ('case_title', models.CharField(max_length=100, verbose_name='사건제목')),
                ('decision_type', models.CharField(choices=[('판결(대법원)', '판결(대법원)'), ('판례(하급심)', '판례(하급심)'), ('심결례', '심결례')], max_length=20, verbose_name='심판유형')),
                ('judge_date', models.DateField(verbose_name='판결선고일')),
                ('judgment_content', models.TextField(blank=True, null=True, verbose_name='판결내용')),
                ('judgment_summary_point', models.TextField(blank=True, null=True, verbose_name='판결요지')),
                ('judgment_issues', models.TextField(blank=True, null=True, verbose_name='판시사항')),
                ('question', models.TextField(blank=True, null=True, verbose_name='질문')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('summary_document', models.TextField(blank=True, null=True, verbose_name='요약원문')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='요약')),
                ('court', models.ForeignKey(db_column='court_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.court')),
            ],
            options={
                'db_table': 'precedents',
            },
        ),
        migrations.CreateModel(
            name='RelationCourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('precedent', models.ForeignKey(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.precedent')),
                ('reference_court_case', models.ForeignKey(db_column='reference_court_cases_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.referencecourtcase')),
            ],
            options={
                'db_table': 'relation_court_cases',
            },
        ),
        migrations.CreateModel(
            name='RelationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('keyword', models.ForeignKey(db_column='keywords_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.keyword')),
                ('precedent', models.ForeignKey(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.precedent')),
            ],
            options={
                'db_table': 'relation_keywords',
            },
        ),
        migrations.CreateModel(
            name='RelationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('outcome_value', models.IntegerField(blank=True, null=True, verbose_name='결과 값')),
                ('outcome', models.ForeignKey(db_column='outcomes_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.outcome')),
                ('precedent', models.ForeignKey(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.precedent')),
            ],
            options={
                'db_table': 'relation_outcomes',
            },
        ),
        migrations.CreateModel(
            name='RelationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('precedent', models.ForeignKey(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.precedent')),
                ('reference_rule', models.ForeignKey(db_column='reference_rules_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.referencerule')),
            ],
            options={
                'db_table': 'relation_rules',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='논리적 삭제 플래그')),
                ('subcategory_name', models.CharField(max_length=50, verbose_name='소분류명')),
                ('category', models.ForeignKey(db_column='categories_id', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='precedents.category')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='precedent',
            name='subcategory',
            field=models.ForeignKey(db_column='subcategories_id', on_delete=django.db.models.deletion.CASCADE, to='precedents.subcategory'),
        ),
    ]
