# Generated by Django 6.0.1 on 2026-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precedent',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='judgment_content',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='judgment_issues',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='judgment_summary_point',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='summary_document',
        ),
        migrations.AddField(
            model_name='precedent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='defendant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='main_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='original_judgment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='petitioner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='pleader',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precedent',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_code',
            field=models.IntegerField(verbose_name='법원 코드'),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(max_length=20, verbose_name='법원 타입'),
        ),
        migrations.AlterField(
            model_name='precedent',
            name='decision_type',
            field=models.CharField(max_length=20, verbose_name='심판유형'),
        ),
        migrations.AlterField(
            model_name='relationoutcome',
            name='outcome_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='court',
            table=None,
        ),
        migrations.AlterModelTable(
            name='keyword',
            table=None,
        ),
        migrations.AlterModelTable(
            name='outcome',
            table=None,
        ),
        migrations.AlterModelTable(
            name='precedent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='referencecourtcase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='referencerule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='relationcourtcase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='relationkeyword',
            table=None,
        ),
        migrations.AlterModelTable(
            name='relationoutcome',
            table=None,
        ),
        migrations.AlterModelTable(
            name='relationrule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table=None,
        ),
    ]
