# Generated by Django 6.0.1 on 2026-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precedent',
            name='case_title',
            field=models.TextField(verbose_name='사건제목'),
        ),
    ]
