# Generated by Django 6.0.1 on 2026-01-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationoutcome',
            name='precedent',
            field=models.OneToOneField(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, related_name='relationoutcome', to='precedents.precedent'),
        ),
    ]
