# Generated by Django 6.0.1 on 2026-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0002_remove_precedent_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precedent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='defendant',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='main_sentence',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='original_judgment',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='petitioner',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='pleader',
        ),
        migrations.RemoveField(
            model_name='precedent',
            name='reason',
        ),
        migrations.AddField(
            model_name='precedent',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='답변'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='holdings',
            field=models.TextField(blank=True, null=True, verbose_name='판시사항'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='judgment_content',
            field=models.TextField(blank=True, null=True, verbose_name='판결내용'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='judgment_summary',
            field=models.TextField(blank=True, null=True, verbose_name='판결요지'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='질문'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='요약'),
        ),
        migrations.AddField(
            model_name='precedent',
            name='summary_original',
            field=models.TextField(blank=True, null=True, verbose_name='요약원문'),
        ),
    ]
