# Generated by Django 6.0.1 on 2026-01-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0003_remove_precedent_content_remove_precedent_defendant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationoutcome',
            name='precedent',
            field=models.OneToOneField(db_column='precedents_id', on_delete=django.db.models.deletion.CASCADE, related_name='relationoutcome', to='precedents.precedent'),
        ),
    ]
