# Generated by Django 6.0.1 on 2026-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0004_alter_precedent_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precedent',
            name='case_no',
            field=models.CharField(max_length=50, verbose_name='사건번호'),
        ),
    ]
