# Generated by Django 6.0.1 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0005_alter_precedent_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precedent',
            name='case_name',
            field=models.TextField(verbose_name='사건명'),
        ),
    ]
