# Generated by Django 6.0.1 on 2026-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0006_alter_precedent_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecourtcase',
            name='ref_case_no',
            field=models.TextField(verbose_name='사건번호'),
        ),
    ]
