# Generated by Django 6.0.1 on 2026-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedents', '0007_alter_referencecourtcase_ref_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecourtcase',
            name='ref_case_no',
            field=models.CharField(max_length=50, verbose_name='사건번호'),
        ),
    ]
